#!/bin/bash

set -e

if [ "$(git diff-index @)" != "" ] && [ "$1" != "--hard" ]; then
    echo "You have uncommitted changes. Please commit them first."
    exit 1
fi


BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

if [ "$BRANCH" = "HEAD" ]; then
    echo "You are not on a branch. Please checkout a branch first."
    exit 1
fi

git push origin -f @:refs/heads/$BRANCH
