#!/bin/bash

red="\033[38;5;1m"
green="\033[38;5;2m"
yellow="\033[38;5;3m"
reset="\033[0m"

git --no-pager log @~1..@
printf "\n"

BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
printf "Current branch: ${yellow}${BRANCH}${reset}\n"
printf "Are you sure you want to overwrite it (y/N): "
read RES;

if [ "$RES" == "y" ]; then
	git add -A
	git commit --amend --no-edit
	git up
else
	printf "${green}Aborting!\n"
fi
